# -*- coding: utf-8 -*-
"""fy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iegdmY0CyJz5D95Z1kwGIGDy0EY3Tchd

# Welcome to Colab!
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='/content/Toronto Island Ferry Tickets.csv'
df=pd.read_csv("Toronto Island Ferry Tickets.csv")
df.head(5)

df.info()

df.describe()

print(df.shape)

print(df.isnull().sum())

print(df.duplicated().sum())

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df.dtypes

df.isnull().sum()

df.duplicated(). sum()

df['_id'].duplicated().sum()

(df['Sales Count'] < 0).sum()

(df['Redemption Count'] < 0).sum()

df['Total Activity'] = (
    df['Sales Count'] + df['Redemption Count']
)

df[['Sales Count', 'Redemption Count', 'Total Activity']].head()

df.nlargest(20, 'Total Activity')

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['Year'] = df['Timestamp'].dt.year
df['Month'] = df['Timestamp'].dt.month
df['Day'] = df['Timestamp'].dt.day
df['Hour'] = df['Timestamp'].dt.hour
df['Minute'] = df['Timestamp'].dt.minute
df['DayOfWeek'] = df['Timestamp'].dt.day_name()

df[['Timestamp', 'Year', 'Month', 'Day', 'Hour', 'Minute', 'DayOfWeek', 'Date']].head()

df['Date'] = df['Timestamp'].dt.date

df['Weekend'] = df['DayOfWeek'].isin(
    ['Saturday', 'Sunday']
)

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

def assign_season(month):
    if month in [5, 6, 7, 8, 9]:
        return 'Summer'
    elif month in [10, 11, 12, 1, 2, 3, 4]:
        return 'Off-Season'

df['Season'] = df['Month'].apply(assign_season)

df['Total Activity Load'] = (
    df['Sales Count'] +
    df['Redemption Count']
)

df['Total Activity Load'] = df['Total Activity']

df[['Sales Count', 'Redemption Count', 'Total Activity Load']].head()

df['Redemption Pressure Ratio'] = (
    df['Redemption Count'] /
    (df['Sales Count'] + 1)
)

df[['Sales Count', 'Redemption Count', 'Redemption Pressure Ratio']].head(5)

df['Redemption Pressure Ratio'].describe()





